name: .NET IIS Deployment

on:
  push:
    branches:
      - main  # or your branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IIS_SERVER_HOST }}
          username: ${{ secrets.IIS_SERVER_USER }}
          password: ${{ secrets.IIS_SERVER_PASS }}
          source: "publish/*"
          target: "C:/inetpub/wwwroot/dotnet"
